/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.andreldm.rcontrol.server.SendKey
 * Method:    sendkey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_andreldm_rcontrol_server_SendKey_sendkey
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
